version: "3.9"

name: test-task

services:
  nginx_local:
    image: nginx:1.25.3-alpine
    container_name: test-task-nginx
    working_dir: /app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - web_local

  web_local:
    container_name: test-task-client
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./src/web:/app
      - /app/node_modules
    depends_on:
      - server_local

  server_local:
    container_name: test-task-server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./src/server:/app
      - /app/node_modules
